// Generated by Wrangler on Sat Jul 27 2024 21:43:29 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	BOT_TOKEN: string;
	SCRIBBLE_GAME_ROOM: DurableObjectNamespace;
	DB: D1Database;
}
