// Generated by Wrangler on Sun Jul 14 2024 11:10:44 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	BOT_TOKEN: string;
	SCRIBBLE_GAME_ROOM: DurableObjectNamespace;
}
